import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/sections/layout";
import localFont from 'next/font/local';


const avenir = localFont({
  src: "../../public/font/AvenirLTStd-Medium.otf",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${avenir.className}`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full box-border px-2 py-4 bg-[#F7FAFC] font-[family-name:var(--font-geist-sans)]">
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
